bug fix in newini.f, sediemnts in netcdf.f

diff --git a/fembin/git-commit b/fembin/git-commit
--- a/fembin/git-commit
+++ b/fembin/git-commit
@@ -8,16 +8,43 @@
 #
 #------------------------------------------------------------------------
 #
-# handles commit and writes to COMMIT file
+# handles commit and writes to COMMIT and VERSION files
+#
+# works both with shyfem and shyfemcm
 #
 #------------------------------------------------------------
-femdir=~/shyfem/
 femdir=.
-fembin=$femdir/fembin
+fembin=$femdir/bin
+
 commit_file=./COMMIT
 version_file=./VERSION
-version_fortran=""		#will be filled in later
+
+shyfem_version=""	# will be filled in later - routine to determine version
+version_fortran=""	# will be filled in later - fortran file with version
 #------------------------------------------------------------
+
+GetVersion()
+{
+  local bin=$fembin
+
+  if [ -x $bin/shyfem_version.pl ]; then
+    shyfem_version=$bin/shyfem_version.pl
+  elif [ -x $bin/shyfem_util/shyfem_version.pl ]; then
+    shyfem_version=$bin/shyfem_util/shyfem_version.pl
+  else
+    echo "*** cannot find shyfem_version.pl ...aborting"
+    exit 13
+  fi
+
+  echo "using $shyfem_version to get version"
+
+  version_line=$( $shyfem_version -noextra $version_file )
+
+  if [ $? -ne 0 ]; then
+    echo "*** error running $shyfem_version ...aborting"
+    exit 9
+  fi
+}
 
 Fetch()
 {
@@ -96,7 +123,12 @@ CheckRules()
 ChangeFortran()
 {
   local file
+
   file=$( tail -1 $version_file )
+  if [ ! -f $file ]; then
+    echo "*** cannot find file: $file ...aborting"
+    exit 7
+  fi
   date=$( date +%Y-%m-%d )
   echo "changing file $file adding date $date to commit"
   perl -p -e "s/(commit\s*=\s*).*/\1\'$date\'/g" $file > aux1.tmp
@@ -104,6 +136,7 @@ ChangeFortran()
   #exit 1
   mv aux2.tmp $file
   rm aux1.tmp
+
   version_fortran=$file
 }
 
@@ -159,20 +192,33 @@ Ask "Do you really want to commit?"
 
 echo "Preparing commit"
 
+#--- change subver.f or version.f90
+
 ChangeFortran
 
-cat log.tmp $commit_file > com.tmp
-mv -f com.tmp $commit_file
-rm -f log.tmp
+#--- change COMMIT
 
-line=`$fembin/shyfem_version.pl -noextra $version_file`
+cat log.tmp $commit_file > com.tmp
+
+#--- change VERSION
+
+GetVersion
 extra=commit_`date +"%Y-%m-%d"`
-echo "$line   $extra"                > ver.tmp
+echo "$version_line   $extra"        > ver.tmp
 echo ""                             >> ver.tmp
 cat $version_file                   >> ver.tmp
+
+#--- copy messages to COMMIT and VERSION
+
+mv -f com.tmp $commit_file
 mv -f ver.tmp $version_file
+rm -f log.tmp
+
+#--- add changed files to actual commit
 
 git add $commit_file $version_file $version_fortran
+
+#--- finally do the commit
 
 git commit -m "$message" --no-verify
 
