bug fix nosresidence, nosaver

diff --git a/fembin/gittar b/fembin/gittar
--- a/fembin/gittar
+++ b/fembin/gittar
@@ -18,7 +18,19 @@ elif [ "$first" = "v" ]; then
   tag=v$vers
 else
   echo "cannot parse version... first: $first"
-  exit 1
+  echo "trying to find commit with this name..."
+  git show $version > /dev/null 2>&1
+  status=$?
+  if [ $status -eq 0 ]; then
+    echo "commit found ... using this version"
+    date=`git show --pretty=format:"%ci" | head -1 | cut -d " " -f 1`
+    echo "commit date: $date"
+    vers=${version}_$date
+    tag=${version}
+  else
+    echo "no such commit found ... aborting"
+    exit 1
+  fi
 fi
 
 prefix=$name-$vers/
